import { Property_row_data } from "@/types";

const propertyColumnNameObj: Property_row_data = {
  company_id: "",
  contact_id: "",
  property_id: "",
  company_name: null,
  contact_name: null,
  company_department_name: null,
  main_phone_number: null,
  main_fax: null,
  zipcode: null,
  address: null,
  company_email: null,
  number_of_employees_class: null,
  capital: null,
  established_in: null,
  business_content: null,
  website_url: null,
  industry_type_id: null,
  country_id: null,
  region_id: null,
  city_id: null,
  product_category_large: null,
  product_category_medium: null,
  product_category_small: null,
  fiscal_end_month: null,
  budget_request_month1: null,
  budget_request_month2: null,
  clients: null,
  supplier: null,
  facility: null,
  business_sites: null,
  overseas_bases: null,
  group_company: null,
  corporate_number: null,
  direct_line: null,
  direct_fax: null,
  extension: null,
  company_cell_phone: null,
  personal_cell_phone: null,
  contact_email: null,
  position_name: null,
  position_class: null,
  occupation: null,
  approval_amount: null,
  contact_created_by_company_id: null,
  contact_created_by_user_id: null,
  contact_created_by_department_of_user: null,
  contact_created_by_unit_of_user: null,
  contact_created_by_office_of_user: null,
  call_careful_flag: false,
  call_careful_reason: null,
  email_ban_flag: false,
  sending_materials_ban_flag: false,
  fax_dm_ban_flag: false,
  ban_reason: null,
  claim: null,
  property_created_at: "2024-03-01",
  property_updated_at: null,
  property_created_by_company_id: null,
  property_created_by_user_id: null,
  property_created_by_department_of_user: null,
  property_created_by_unit_of_user: null,
  property_created_by_office_of_user: null,
  client_contact_id: null,
  client_company_id: null,
  current_status: null,
  property_name: null,
  property_summary: null,
  pending_flag: false,
  rejected_flag: false,
  expected_product_id: null,
  expected_product: null,
  product_sales: null,
  expected_order_date: null,
  expected_sales_price: null,
  term_division: null,
  sold_product_id: null,
  sold_product: null,
  unit_sales: null,
  sales_contribution_category: null,
  sales_price: null,
  discounted_price: null,
  discount_rate: null,
  sales_class: null,
  expansion_date: null,
  sales_date: null,
  expansion_quarter: null,
  sales_quarter: null,
  subscription_start_date: null,
  subscription_canceled_at: null,
  leasing_company: null,
  lease_division: null,
  lease_expiration_date: null,
  step_in_flag: false,
  repeat_flag: false,
  order_certainty_start_of_month: null,
  review_order_certainty: null,
  competitor_appearance_date: null,
  competitor: null,
  competitor_product: null,
  reason_class: null,
  reason_detail: null,
  customer_budget: null,
  decision_maker_negotiation: null,
  expansion_year_month: null,
  sales_year_month: null,
  subscription_interval: null,
  competition_state: null,
  property_year_month: null,
  property_department: null,
  property_business_office: null,
  property_member_name: null,
  property_date: null,
  assigned_department_name: null,
  assigned_unit_name: null,
  assigned_office_name: null,
};

export const SEED_CARDS = Array(11)
  .fill(null)
  .map((_, index) => {
    let columnName = 1;
    if (4 < index && index < 8) columnName = 2;
    if (8 <= index && index <= 9) columnName = 3;
    if (10 <= index) columnName = 4;

    return {
      ...propertyColumnNameObj,
      company_id: index.toString(),
      contact_id: index.toString(),
      property_id: index.toString(),
      company_name: `株式会社キーエンス ${index}`,
      property_summary: "次回見積持って社長商談",
      expected_product: `IM${index}`,
      expected_sales_price: `${6000000 + index}`,
      expansion_date: new Date().toISOString(),
      column_title_num: columnName,
    };
  });
