export const rightRowData = [
  {
    activityType: `TEL発信`,
    summary: "アポ取得。7/5の15時から30分なら打ち合わせOK。見積書も準備する。",
    date: "2021/07/02",
    sales: "伊藤謙太",
    department: "営業一部",
    office: "東京営業所",
  },
  {
    activityType: `TEL発信(不在)`,
    summary: "0907 席外し",
    date: "2021/07/02",
    sales: "須田優太郎",
    department: "営業一部",
    office: "横浜営業所",
  },
  {
    activityType: `訪問`,
    summary: "PR会 担当は反応良いが、上長同席できず商談まではできず。再訪必要。",
    date: "2021/06/28",
    sales: "高橋優斗",
    department: "営業一部",
    office: "海老名営業所",
  },
  {
    activityType: `TEL発信`,
    summary: "席外し、14時頃戻ると",
    date: "2021/06/25",
    sales: "金本光弘",
    department: "営業一部",
    office: "海老名営業所",
  },
  {
    activityType: `見積`,
    summary: "",
    date: "2021/06/23",
    sales: "新井信介",
    department: "営業一部",
    office: "横浜営業所",
  },
  {
    activityType: `TEL発信`,
    summary: "アポ取得。 28日8:30からOK。当日上長同席呼びかける",
    date: "2021/06/22",
    sales: "高橋優斗",
    department: "営業一部",
    office: "海老名営業所",
  },
  {
    activityType: `訪問`,
    summary: "反応良い。見積もり持ってきてと。",
    date: "2021/06/23",
    sales: "新井信介",
    department: "営業一部",
    office: "横浜営業所",
  },
];
