export const rightRowData = [
  {
    activity_type: `TEL発信`,
    summary: "アポ取得。7/5の15時から30分なら打ち合わせOK。見積書も準備する。",
    activity_date: "2021/07/02",
    our_member_name: "伊藤謙太",
    our_department: "営業一部",
    our_office: "東京営業所",
  },
  {
    activity_type: `TEL発信(不在)`,
    summary: "0907 席外し",
    activity_date: "2021/07/02",
    our_member_name: "須田優太郎",
    our_department: "営業一部",
    our_office: "横浜営業所",
  },
  {
    activity_type: `訪問`,
    summary: "PR会 担当は反応良いが、上長同席できず商談まではできず。再訪必要。",
    activity_date: "2021/06/28",
    our_member_name: "高橋優斗",
    our_department: "営業一部",
    our_office: "海老名営業所",
  },
  {
    activity_type: `TEL発信`,
    summary: "席外し、14時頃戻ると",
    activity_date: "2021/06/25",
    our_member_name: "金本光弘",
    our_department: "営業一部",
    our_office: "海老名営業所",
  },
  {
    activity_type: `見積`,
    summary: "",
    activity_date: "2021/06/23",
    our_member_name: "新井信介",
    our_department: "営業一部",
    our_office: "横浜営業所",
  },
  {
    activity_type: `TEL発信`,
    summary: "アポ取得。 28日8:30からOK。当日上長同席呼びかける",
    activity_date: "2021/06/22",
    our_member_name: "高橋優斗",
    our_department: "営業一部",
    our_office: "海老名営業所",
  },
  {
    activity_type: `訪問`,
    summary: "反応良い。見積もり持ってきてと。",
    activity_date: "2021/06/23",
    our_member_name: "新井信介",
    our_department: "営業一部",
    our_office: "横浜営業所",
  },
  {
    activity_type: `TEL発信`,
    summary: "アポ取得。7/5の15時から30分なら打ち合わせOK。見積書も準備する。",
    activity_date: "2021/07/02",
    our_member_name: "伊藤謙太",
    our_department: "営業一部",
    our_office: "東京営業所",
  },
  {
    activity_type: `TEL発信(不在)`,
    summary: "0907 席外し",
    activity_date: "2021/07/02",
    our_member_name: "須田優太郎",
    our_department: "営業一部",
    our_office: "横浜営業所",
  },
  {
    activity_type: `訪問`,
    summary: "PR会 担当は反応良いが、上長同席できず商談まではできず。再訪必要。",
    activity_date: "2021/06/28",
    our_member_name: "高橋優斗",
    our_department: "営業一部",
    our_office: "海老名営業所",
  },
  {
    activity_type: `TEL発信`,
    summary: "席外し、14時頃戻ると",
    activity_date: "2021/06/25",
    our_member_name: "金本光弘",
    our_department: "営業一部",
    our_office: "海老名営業所",
  },
  {
    activity_type: `見積`,
    summary: "",
    activity_date: "2021/06/23",
    our_member_name: "新井信介",
    our_department: "営業一部",
    our_office: "横浜営業所",
  },
  {
    activity_type: `TEL発信`,
    summary: "アポ取得。 28日8:30からOK。当日上長同席呼びかける",
    activity_date: "2021/06/22",
    our_member_name: "高橋優斗",
    our_department: "営業一部",
    our_office: "海老名営業所",
  },
  {
    activity_type: `訪問`,
    summary: "反応良い。見積もり持ってきてと。",
    activity_date: "2021/06/23",
    our_member_name: "新井信介",
    our_department: "営業一部",
    our_office: "横浜営業所",
  },
  {
    activity_type: `TEL発信`,
    summary: "アポ取得。7/5の15時から30分なら打ち合わせOK。見積書も準備する。",
    activity_date: "2021/07/02",
    our_member_name: "伊藤謙太",
    our_department: "営業一部",
    our_office: "東京営業所",
  },
  {
    activity_type: `TEL発信(不在)`,
    summary: "0907 席外し",
    activity_date: "2021/07/02",
    our_member_name: "須田優太郎",
    our_department: "営業一部",
    our_office: "横浜営業所",
  },
  {
    activity_type: `訪問`,
    summary: "PR会 担当は反応良いが、上長同席できず商談まではできず。再訪必要。",
    activity_date: "2021/06/28",
    our_member_name: "高橋優斗",
    our_department: "営業一部",
    our_office: "海老名営業所",
  },
  {
    activity_type: `TEL発信`,
    summary: "席外し、14時頃戻ると",
    activity_date: "2021/06/25",
    our_member_name: "金本光弘",
    our_department: "営業一部",
    our_office: "海老名営業所",
  },
  {
    activity_type: `見積`,
    summary: "",
    activity_date: "2021/06/23",
    our_member_name: "新井信介",
    our_department: "営業一部",
    our_office: "横浜営業所",
  },
  {
    activity_type: `TEL発信`,
    summary: "アポ取得。 28日8:30からOK。当日上長同席呼びかける",
    activity_date: "2021/06/22",
    our_member_name: "高橋優斗",
    our_department: "営業一部",
    our_office: "海老名営業所",
  },
  {
    activity_type: `訪問`,
    summary: "反応良い。見積もり持ってきてと。",
    activity_date: "2021/06/23",
    our_member_name: "新井信介",
    our_department: "営業一部",
    our_office: "横浜営業所",
  },
  {
    activity_type: `TEL発信`,
    summary: "アポ取得。7/5の15時から30分なら打ち合わせOK。見積書も準備する。",
    activity_date: "2021/07/02",
    our_member_name: "伊藤謙太",
    our_department: "営業一部",
    our_office: "東京営業所",
  },
  {
    activity_type: `TEL発信(不在)`,
    summary: "0907 席外し",
    activity_date: "2021/07/02",
    our_member_name: "須田優太郎",
    our_department: "営業一部",
    our_office: "横浜営業所",
  },
  {
    activity_type: `訪問`,
    summary: "反応良い。見積もり持ってきてと。",
    activity_date: "2021/06/23",
    our_member_name: "新井信介",
    our_department: "営業一部",
    our_office: "横浜営業所",
  },
  {
    activity_type: `TEL発信`,
    summary: "アポ取得。7/5の15時から30分なら打ち合わせOK。見積書も準備する。",
    activity_date: "2021/07/02",
    our_member_name: "伊藤謙太",
    our_department: "営業一部",
    our_office: "東京営業所",
  },
  {
    activity_type: `TEL発信(不在)`,
    summary: "0907 席外し",
    activity_date: "2021/07/02",
    our_member_name: "須田優太郎",
    our_department: "営業一部",
    our_office: "横浜営業所",
  },
  {
    activity_type: `訪問`,
    summary: "PR会 担当は反応良いが、上長同席できず商談まではできず。再訪必要。",
    activity_date: "2021/06/28",
    our_member_name: "高橋優斗",
    our_department: "営業一部",
    our_office: "海老名営業所",
  },
  {
    activity_type: `TEL発信`,
    summary: "席外し、14時頃戻ると",
    activity_date: "2021/06/25",
    our_member_name: "金本光弘",
    our_department: "営業一部",
    our_office: "海老名営業所",
  },
  {
    activity_type: `見積`,
    summary: "",
    activity_date: "2021/06/23",
    our_member_name: "新井信介",
    our_department: "営業一部",
    our_office: "横浜営業所",
  },
  {
    activity_type: `TEL発信`,
    summary: "アポ取得。 28日8:30からOK。当日上長同席呼びかける",
    activity_date: "2021/06/22",
    our_member_name: "高橋優斗",
    our_department: "営業一部",
    our_office: "海老名営業所",
  },
  {
    activity_type: `訪問`,
    summary: "反応良い。見積もり持ってきてと。",
    activity_date: "2021/06/23",
    our_member_name: "新井信介",
    our_department: "営業一部",
    our_office: "横浜営業所",
  },
  {
    activity_type: `TEL発信`,
    summary: "アポ取得。7/5の15時から30分なら打ち合わせOK。見積書も準備する。",
    activity_date: "2021/07/02",
    our_member_name: "伊藤謙太",
    our_department: "営業一部",
    our_office: "東京営業所",
  },
  {
    activity_type: `TEL発信(不在)`,
    summary: "0907 席外し",
    activity_date: "2021/07/02",
    our_member_name: "須田優太郎",
    our_department: "営業一部",
    our_office: "横浜営業所",
  },
  // 40-50
  {
    activity_type: `訪問`,
    summary: "反応良い。見積もり持ってきてと。",
    activity_date: "2021/06/23",
    our_member_name: "新井信介",
    our_department: "営業一部",
    our_office: "横浜営業所",
  },
  {
    activity_type: `TEL発信`,
    summary: "アポ取得。7/5の15時から30分なら打ち合わせOK。見積書も準備する。",
    activity_date: "2021/07/02",
    our_member_name: "伊藤謙太",
    our_department: "営業一部",
    our_office: "東京営業所",
  },
  {
    activity_type: `TEL発信(不在)`,
    summary: "0907 席外し",
    activity_date: "2021/07/02",
    our_member_name: "須田優太郎",
    our_department: "営業一部",
    our_office: "横浜営業所",
  },
  {
    activity_type: `訪問`,
    summary: "PR会 担当は反応良いが、上長同席できず商談まではできず。再訪必要。",
    activity_date: "2021/06/28",
    our_member_name: "高橋優斗",
    our_department: "営業一部",
    our_office: "海老名営業所",
  },
  {
    activity_type: `TEL発信`,
    summary: "席外し、14時頃戻ると",
    activity_date: "2021/06/25",
    our_member_name: "金本光弘",
    our_department: "営業一部",
    our_office: "海老名営業所",
  },
  {
    activity_type: `見積`,
    summary: "",
    activity_date: "2021/06/23",
    our_member_name: "新井信介",
    our_department: "営業一部",
    our_office: "横浜営業所",
  },
  {
    activity_type: `TEL発信`,
    summary: "アポ取得。 28日8:30からOK。当日上長同席呼びかける",
    activity_date: "2021/06/22",
    our_member_name: "高橋優斗",
    our_department: "営業一部",
    our_office: "海老名営業所",
  },
  {
    activity_type: `訪問`,
    summary: "反応良い。見積もり持ってきてと。",
    activity_date: "2021/06/23",
    our_member_name: "新井信介",
    our_department: "営業一部",
    our_office: "横浜営業所",
  },
  {
    activity_type: `TEL発信`,
    summary: "アポ取得。7/5の15時から30分なら打ち合わせOK。見積書も準備する。",
    activity_date: "2021/07/02",
    our_member_name: "伊藤謙太",
    our_department: "営業一部",
    our_office: "東京営業所",
  },
  {
    activity_type: `TEL発信(不在)`,
    summary: "0907 席外し",
    activity_date: "2021/07/02",
    our_member_name: "須田優太郎",
    our_department: "営業一部",
    our_office: "横浜営業所",
  },
];
